theme: minima
title: Dejah Ecckles Software Developemt Porfolio
author: Dejah Ecckles
description: A professional portfolio of all my projects proving my skills and understand of the different areas of Software Development
