theme: minima
title: Dejah Ecckles Software Development Portfolio
author: Dejah Ecckles
description: A professional portfolio of all my projects proving my skills and understanding of the different areas of Software Development
